"""Apple Shortcuts backend for the high-level py2shortcuts IR."""

from __future__ import annotations

from dataclasses import dataclass
import uuid

from .. import ir
from ..errors import CompileError
from ..plist import Action, PlistValue, Workflow, action, raw_action, workflow
from ..plugins import PluginRegistry


@dataclass(frozen=True, slots=True)
class ValueRef:
    """A value available to a later Shortcuts action."""

    kind: str
    name: str
    output_name: str | None = None
    aggrandizements: tuple[dict[str, PlistValue], ...] = ()

    @classmethod
    def action(cls, action_value: Action, output_name: str) -> "ValueRef":
        parameters = action_value["WFWorkflowActionParameters"]
        if not isinstance(parameters, dict):
            raise ValueError("Action has no parameters")
        action_uuid = parameters.get("UUID")
        if not isinstance(action_uuid, str):
            raise ValueError("Action has no UUID")
        return cls("action", action_uuid, output_name)

    @classmethod
    def variable(cls, name: str) -> "ValueRef":
        return cls("variable", name)

    @classmethod
    def shortcut_input(cls) -> "ValueRef":
        return cls("shortcut_input", "Shortcut Input")

    def coerced(self, item_class: str) -> "ValueRef":
        return ValueRef(
            self.kind,
            self.name,
            self.output_name,
            (*self.aggrandizements, {
                "Type": "WFCoercionVariableAggrandizement",
                "CoercionItemClass": item_class,
            }),
        )

    def value(self) -> dict[str, PlistValue]:
        if self.kind == "action":
            assert self.output_name is not None
            value: dict[str, PlistValue] = {
                "OutputUUID": self.name,
                "OutputName": self.output_name,
                "Type": "ActionOutput",
            }
        elif self.kind == "variable":
            value = {"VariableName": self.name, "Type": "Variable"}
        elif self.kind == "shortcut_input":
            value = {"Type": "ExtensionInput"}
        else:
            raise ValueError(f"Unknown reference kind {self.kind!r}")
        if self.aggrandizements:
            value["Aggrandizements"] = list(self.aggrandizements)
        return value

    def attachment(self) -> dict[str, PlistValue]:
        return {
            "Value": self.value(),
            "WFSerializationType": "WFTextTokenAttachment",
        }

    def condition_input(self) -> dict[str, PlistValue]:
        return {"Type": "Variable", "Variable": self.attachment()}


class ShortcutsBackend:
    """Lower py2shortcuts IR into Apple's flat ``WFWorkflowActions`` stream."""

    def __init__(
        self,
        *,
        name: str,
        plugins: PluginRegistry | None = None,
        include_header_comment: bool = True,
        input_classes: tuple[str, ...] = (),
        workflow_types: tuple[str, ...] = (),
    ) -> None:
        self.name = name
        self.actions: list[Action] = []
        self.plugins = default_plugin_registry()
        if plugins is not None:
            self.plugins.extend(plugins)
        self.include_header_comment = include_header_comment
        self.input_classes = input_classes
        self.workflow_types = workflow_types
        self.uses_shortcut_input = False
        self.loop_depth = 0
        self._temp_counter = 0
        self.var_types: dict[str, str] = {}

    def compile(self, module: ir.Module) -> Workflow:
        if self.include_header_comment:
            self.actions.append(
                action(
                    "comment",
                    WFCommentActionText=(
                        "Generated by py2shortcuts. Treat the Python source as the source of truth; "
                        "manual edits to this generated workflow may be overwritten."
                    ),
                )
            )
        for statement in module.body:
            self.emit_stmt(statement)
        if self.uses_shortcut_input and not self.input_classes:
            raise CompileError(
                "ios.shortcuts.shortcut_input() requires shortcut.input.types in py2shortcuts.toml"
            )
        return workflow(
            self.actions,
            name=self.name,
            input_classes=self.input_classes,
            workflow_types=self.workflow_types,
            has_shortcut_input=self.uses_shortcut_input,
        )

    def emit_stmt(self, statement: ir.Stmt) -> None:
        if isinstance(statement, ir.Assign):
            value = self.require_value(self.emit_expr(statement.value), context=f"assignment to {statement.name}")
            self.actions.append(action("setvariable", WFVariableName=statement.name, WFInput=value.attachment()))
            self.var_types[statement.name] = self.expr_type(statement.value)
            return

        if isinstance(statement, ir.ExprStmt):
            self.emit_expr(statement.value)
            return

        if isinstance(statement, ir.AppendStmt):
            value = self.require_value(self.emit_expr(statement.value), context=f"append to {statement.target}")
            self.actions.append(
                action("appendvariable", WFVariableName=statement.target, WFInput=value.attachment())
            )
            self.var_types[statement.target] = "list"
            return

        if isinstance(statement, ir.IfStmt):
            self.emit_if(statement)
            return

        if isinstance(statement, ir.ForEachStmt):
            self.emit_for_each(statement)
            return

        if isinstance(statement, ir.ForRangeStmt):
            self.emit_for_range(statement)
            return

        raise CompileError(f"Shortcuts backend cannot lower {type(statement).__name__}")

    def emit_expr(self, expression: ir.Expr) -> ValueRef | None:
        if isinstance(expression, ir.Literal):
            return self.emit_literal(expression.value)

        if isinstance(expression, ir.Var):
            return ValueRef.variable(expression.name)

        if isinstance(expression, ir.Symbol):
            raise CompileError(f"compile-time symbol {expression.name!r} cannot be used as a runtime value")

        if isinstance(expression, ir.BlockExpr):
            for statement in expression.body:
                self.emit_stmt(statement)
            return self.emit_expr(expression.result)

        if isinstance(expression, ir.Binary):
            return self.emit_binary(expression)

        if isinstance(expression, ir.Unary):
            if expression.op == "+":
                return self.require_value(self.emit_expr(expression.operand), context="unary +")
            if expression.op == "-":
                operand = self.require_value(self.emit_expr(expression.operand), context="unary -")
                zero = self.emit_literal(0)
                assert zero is not None
                return self.emit_math(zero, "-", operand)
            if expression.op == "not":
                return self.emit_not(expression.operand)
            raise CompileError(f"unsupported unary operation {expression.op!r}")

        if isinstance(expression, ir.Compare):
            return self.materialize_condition(expression)

        if isinstance(expression, ir.BoolExpr):
            return self.materialize_condition(expression)

        if isinstance(expression, ir.Call):
            return self.emit_call(expression)

        if isinstance(expression, ir.ListExpr):
            return self.emit_list(expression)

        if isinstance(expression, ir.DictExpr):
            return self.emit_dict(expression)

        if isinstance(expression, ir.Subscript):
            return self.emit_subscript(expression)

        if isinstance(expression, ir.FormatString):
            text = self.text_token_from_parts(expression.parts)
            value = action("gettext", WFTextActionText=text)
            self.actions.append(value)
            return ValueRef.action(value, "Text")

        raise CompileError(f"Shortcuts backend cannot lower expression {type(expression).__name__}")

    def emit_literal(self, value: ir.Scalar) -> ValueRef:
        if isinstance(value, str) or value is None:
            result = action("gettext", WFTextActionText="" if value is None else value)
            self.actions.append(result)
            return ValueRef.action(result, "Text")
        if isinstance(value, bool):
            result = action("number", WFNumberActionNumber="1" if value else "0")
            self.actions.append(result)
            return ValueRef.action(result, "Number")
        if isinstance(value, (int, float)):
            result = action("number", WFNumberActionNumber=self.scalar_text(value))
            self.actions.append(result)
            return ValueRef.action(result, "Number")
        raise CompileError(f"unsupported literal {value!r}")

    def emit_binary(self, expression: ir.Binary) -> ValueRef:
        left = self.require_value(self.emit_expr(expression.left), context=f"left operand of {expression.op}")
        if expression.op not in {"+", "-", "*", "/", "%", "**"}:
            raise CompileError(f"unsupported binary operation {expression.op!r}")

        if expression.op in {"%", "**"}:
            if isinstance(expression.right, ir.Literal) and isinstance(expression.right.value, (int, float, bool)):
                right_parameter: PlistValue = self.scalar_text(expression.right.value)
            else:
                right = self.require_value(self.emit_expr(expression.right), context=f"right operand of {expression.op}")
                right_parameter = right.attachment()
            scientific = "Modulus" if expression.op == "%" else "Power"
            result = action(
                "math",
                WFInput=left.attachment(),
                WFMathOperation="…",
                WFScientificMathOperation=scientific,
                WFScientificMathOperand=right_parameter,
            )
            self.actions.append(result)
            return ValueRef.action(result, "Calculation Result")

        if isinstance(expression.right, ir.Literal) and isinstance(expression.right.value, (int, float, bool)):
            right_value: PlistValue = self.scalar_text(expression.right.value)
        else:
            right = self.require_value(self.emit_expr(expression.right), context=f"right operand of {expression.op}")
            right_value = right.attachment()
        return self.emit_math(left, expression.op, right_value)

    def emit_math(self, left: ValueRef, operator: str, right: ValueRef | PlistValue) -> ValueRef:
        op = {"+": "+", "-": "-", "*": "×", "/": "÷"}.get(operator)
        if op is None:
            raise CompileError(f"no native math mapping for {operator!r}")
        operand: PlistValue = right.attachment() if isinstance(right, ValueRef) else right
        result = action("math", WFInput=left.attachment(), WFMathOperation=op, WFMathOperand=operand)
        self.actions.append(result)
        return ValueRef.action(result, "Calculation Result")

    def emit_list(self, expression: ir.ListExpr) -> ValueRef:
        # The List action's WFItems field is text-oriented. Embedding dynamic
        # numeric ActionOutputs there via WFTextTokenString coerces them to
        # text, which later breaks arithmetic (notably list comprehensions over
        # decoded image pixels). Materialize Python lists as a real mutable
        # Shortcuts variable and append each value with Add to Variable so item
        # types are preserved.
        values = [
            self.require_value(self.emit_expr(item), context="list item")
            for item in expression.items
        ]
        return self.emit_runtime_list(values)

    def emit_runtime_list(self, values: list[ValueRef]) -> ValueRef:
        empty = action("list", WFItems=[])
        self.actions.append(empty)

        name = self.new_temp_variable("list")
        self.actions.append(
            action(
                "setvariable",
                WFVariableName=name,
                WFInput=ValueRef.action(empty, "List").attachment(),
            )
        )
        self.var_types[name] = "list"

        for value in values:
            self.actions.append(
                action("appendvariable", WFVariableName=name, WFInput=value.attachment())
            )

        return ValueRef.variable(name)

    def emit_dict(self, expression: ir.DictExpr) -> ValueRef:
        fields: list[PlistValue] = []
        for key_expr, value_expr in expression.items:
            if not isinstance(key_expr, ir.Literal) or not isinstance(key_expr.value, str):
                raise CompileError("Shortcuts dictionary keys must currently be literal strings")
            key = self.static_text_token(key_expr.value)
            if isinstance(value_expr, ir.Literal) and isinstance(value_expr.value, str):
                value: PlistValue = self.static_text_token(value_expr.value)
            else:
                ref = self.require_value(self.emit_expr(value_expr), context="dictionary value")
                value = self.text_token_from_refs((ref,))
            fields.append({"WFItemType": 0, "WFKey": key, "WFValue": value})
        result = action(
            "dictionary",
            WFItems={
                "Value": {"WFDictionaryFieldValueItems": fields},
                "WFSerializationType": "WFDictionaryFieldValue",
            },
        )
        self.actions.append(result)
        return ValueRef.action(result, "Dictionary")

    def emit_subscript(self, expression: ir.Subscript) -> ValueRef:
        base = self.require_value(self.emit_expr(expression.value), context="subscript base")
        key = expression.key
        if isinstance(key, ir.Literal) and isinstance(key.value, str):
            result = action("getvalueforkey", WFInput=base.attachment(), WFDictionaryKey=key.value)
            self.actions.append(result)
            return ValueRef.action(result, "Dictionary Value")
        if isinstance(key, ir.Literal) and isinstance(key.value, int) and not isinstance(key.value, bool):
            if key.value < 0:
                raise CompileError("negative list indexes are not supported yet")
            result = action(
                "getitemfromlist",
                WFInput=base.attachment(),
                WFItemSpecifier="Item At Index",
                WFItemIndex=str(key.value + 1),  # Shortcuts indexes from 1; Python indexes from 0.
            )
            self.actions.append(result)
            return ValueRef.action(result, "Item from List")
        raise CompileError("subscript keys must currently be a literal string or non-negative integer")

    def emit_call(self, call: ir.Call) -> ValueRef | None:
        if call.target == "print":
            return self.emit_print(call)
        if call.target == "input":
            return self.emit_input(call)
        if call.target == "len":
            return self.emit_len(call)
        if call.target == "range":
            raise CompileError("range() is only supported directly in a for loop")

        lowerer = self.plugins.get_call(call.target)
        if lowerer is not None:
            return lowerer(self, call)
        raise CompileError(
            f"no Shortcuts lowering is registered for call {call.target}(); "
            "add a backend plugin/adapter"
        )

    def emit_print(self, call: ir.Call) -> None:
        allowed = {"sep", "end"}
        unknown = {name for name, _ in call.kwargs} - allowed
        if unknown:
            raise CompileError(f"print() does not support keyword(s): {', '.join(sorted(unknown))}")
        sep_expr = call.keyword("sep")
        end_expr = call.keyword("end")
        sep = self.require_literal_string(sep_expr, default=" ", name="print sep")
        end = self.require_literal_string(end_expr, default="\n", name="print end")

        parts: list[str | ir.Expr] = []
        for index, argument in enumerate(call.args):
            if index:
                parts.append(sep)
            parts.append(argument)
        parts.append(end)
        text = self.text_token_from_parts(tuple(parts))
        self.actions.append(action("showresult", Text=text))
        return None

    def emit_input(self, call: ir.Call) -> ValueRef:
        if len(call.args) > 1:
            raise CompileError("input() accepts at most one prompt")
        if call.kwargs:
            raise CompileError("input() keyword arguments are not supported")
        prompt: PlistValue = ""
        if call.args:
            prompt = self.text_param(call.args[0])
        result = action("ask", WFAskActionPrompt=prompt, WFInputType="Text")
        self.actions.append(result)
        return ValueRef.action(result, "Provided Input")

    def emit_len(self, call: ir.Call) -> ValueRef:
        if len(call.args) != 1 or call.kwargs:
            raise CompileError("len() expects exactly one positional argument")
        value = self.require_value(self.emit_expr(call.args[0]), context="len()")
        attachment = value.attachment()
        result = action("count", WFCountType="Items", WFInput=attachment, Input=attachment)
        self.actions.append(result)
        return ValueRef.action(result, "Count")

    def emit_if(self, statement: ir.IfStmt) -> None:
        group = self.new_uuid()
        params = self.condition_params(statement.condition)
        self.actions.append(action("conditional", GroupingIdentifier=group, WFControlFlowMode=0, **params))
        for child in statement.body:
            self.emit_stmt(child)
        if statement.orelse:
            self.actions.append(action("conditional", GroupingIdentifier=group, WFControlFlowMode=1))
            for child in statement.orelse:
                self.emit_stmt(child)
        self.actions.append(action("conditional", GroupingIdentifier=group, WFControlFlowMode=2))

    def emit_for_each(self, statement: ir.ForEachStmt) -> None:
        iterable = self.require_value(self.emit_expr(statement.iterable), context="for iterable")
        group = self.new_uuid()
        repeat_start = action(
            "repeat.each",
            GroupingIdentifier=group,
            WFControlFlowMode=0,
            WFInput=iterable.attachment(),
        )
        self.actions.append(repeat_start)
        self.loop_depth += 1
        try:
            repeat_item = ValueRef.variable(self.repeat_variable_name("Repeat Item"))
            self.actions.append(action("setvariable", WFVariableName=statement.target, WFInput=repeat_item.attachment()))
            self.var_types[statement.target] = "unknown"
            for child in statement.body:
                self.emit_stmt(child)
        finally:
            self.loop_depth -= 1
        self.actions.append(action("repeat.each", GroupingIdentifier=group, WFControlFlowMode=2))

    def emit_for_range(self, statement: ir.ForRangeStmt) -> None:
        if not isinstance(statement.step, ir.Literal) or statement.step.value != 1:
            raise CompileError("Shortcuts backend currently supports only range(..., step=1)")

        count_param: PlistValue
        if (
            isinstance(statement.start, ir.Literal)
            and isinstance(statement.stop, ir.Literal)
            and isinstance(statement.start.value, int)
            and not isinstance(statement.start.value, bool)
            and isinstance(statement.stop.value, int)
            and not isinstance(statement.stop.value, bool)
        ):
            count_param = max(0, statement.stop.value - statement.start.value)
        elif isinstance(statement.start, ir.Literal) and statement.start.value == 0:
            stop = self.require_value(self.emit_expr(statement.stop), context="range stop")
            count_param = stop.attachment()
        else:
            count = self.emit_binary(ir.Binary("-", statement.stop, statement.start))
            count_param = count.attachment()

        group = self.new_uuid()
        repeat_start = action(
            "repeat.count",
            GroupingIdentifier=group,
            WFControlFlowMode=0,
            WFRepeatCount=count_param,
        )
        self.actions.append(repeat_start)
        self.loop_depth += 1
        try:
            index = ValueRef.variable(self.repeat_variable_name("Repeat Index"))
            if isinstance(statement.start, ir.Literal) and isinstance(statement.start.value, (int, float)):
                target_value = self.emit_math(index, "+", self.scalar_text(statement.start.value - 1))
            else:
                start = self.require_value(self.emit_expr(statement.start), context="range start")
                combined = self.emit_math(start, "+", index)
                target_value = self.emit_math(combined, "-", "1")
            self.actions.append(action("setvariable", WFVariableName=statement.target, WFInput=target_value.attachment()))
            self.var_types[statement.target] = "number"
            for child in statement.body:
                self.emit_stmt(child)
        finally:
            self.loop_depth -= 1
        self.actions.append(action("repeat.count", GroupingIdentifier=group, WFControlFlowMode=2))

    def materialize_condition(self, expression: ir.Expr) -> ValueRef:
        if isinstance(expression, ir.Literal):
            return self.emit_literal(bool(expression.value))

        if isinstance(expression, ir.Unary) and expression.op == "not":
            value = self.materialize_condition(expression.operand)
            return self.branch_boolean(value, when_true=False)

        if isinstance(expression, ir.BoolExpr):
            if not expression.values:
                return self.emit_literal(expression.op == "and")
            current = self.materialize_condition(expression.values[0])
            for value_expr in expression.values[1:]:
                group = self.new_uuid()
                self.actions.append(
                    action(
                        "conditional",
                        GroupingIdentifier=group,
                        WFControlFlowMode=0,
                        **self.ref_equals_params(current, "1"),
                    )
                )
                if expression.op == "and":
                    branch = self.materialize_condition(value_expr)
                    self.actions.append(action("conditional", GroupingIdentifier=group, WFControlFlowMode=1))
                    self.emit_literal(False)
                else:
                    self.emit_literal(True)
                    self.actions.append(action("conditional", GroupingIdentifier=group, WFControlFlowMode=1))
                    branch = self.materialize_condition(value_expr)
                end = action("conditional", GroupingIdentifier=group, WFControlFlowMode=2)
                self.actions.append(end)
                current = ValueRef.action(end, "If Result")
                _ = branch  # branch output is consumed implicitly as the last branch action.
            return current

        group = self.new_uuid()
        params = self.condition_params(expression, materializing=True)
        self.actions.append(action("conditional", GroupingIdentifier=group, WFControlFlowMode=0, **params))
        self.emit_literal(True)
        self.actions.append(action("conditional", GroupingIdentifier=group, WFControlFlowMode=1))
        self.emit_literal(False)
        end = action("conditional", GroupingIdentifier=group, WFControlFlowMode=2)
        self.actions.append(end)
        return ValueRef.action(end, "If Result")

    def emit_not(self, expression: ir.Expr) -> ValueRef:
        value = self.materialize_condition(expression)
        return self.branch_boolean(value, when_true=False)

    def branch_boolean(self, value: ValueRef, *, when_true: bool) -> ValueRef:
        group = self.new_uuid()
        self.actions.append(
            action(
                "conditional",
                GroupingIdentifier=group,
                WFControlFlowMode=0,
                **self.ref_equals_params(value, "1"),
            )
        )
        self.emit_literal(when_true)
        self.actions.append(action("conditional", GroupingIdentifier=group, WFControlFlowMode=1))
        self.emit_literal(not when_true)
        end = action("conditional", GroupingIdentifier=group, WFControlFlowMode=2)
        self.actions.append(end)
        return ValueRef.action(end, "If Result")

    def condition_params(self, expression: ir.Expr, *, materializing: bool = False) -> dict[str, PlistValue]:
        if isinstance(expression, ir.Compare):
            left = self.require_value(self.emit_expr(expression.left), context="comparison left side")
            right = expression.right
            if right == ir.Literal(None):
                if expression.op == "==":
                    return {"WFInput": left.condition_input(), "WFCondition": 101}
                if expression.op == "!=":
                    return {"WFInput": left.condition_input(), "WFCondition": 100}
                raise CompileError("None supports only == and != comparisons")

            if expression.op in {"<", "<=", ">", ">="}:
                code = {"<": 0, "<=": 1, ">": 2, ">=": 3}[expression.op]
                if isinstance(right, ir.Literal) and isinstance(right.value, (int, float, bool)):
                    operand: PlistValue = self.scalar_text(right.value)
                else:
                    operand_ref = self.require_value(self.emit_expr(right), context="numeric comparison right side")
                    operand = operand_ref.attachment()
                return {"WFInput": left.condition_input(), "WFCondition": code, "WFNumberValue": operand}

            if expression.op in {"==", "!="}:
                code = 4 if expression.op == "==" else 5
                if isinstance(right, ir.Literal):
                    comparison: PlistValue = "" if right.value is None else self.scalar_text(right.value)
                else:
                    right_ref = self.require_value(self.emit_expr(right), context="comparison right side")
                    comparison = self.text_token_from_refs((right_ref,))
                return {
                    "WFInput": left.condition_input(),
                    "WFCondition": code,
                    "WFConditionalActionString": comparison,
                }
            raise CompileError(f"unsupported comparison {expression.op!r}")

        if isinstance(expression, (ir.BoolExpr,)) or (isinstance(expression, ir.Unary) and expression.op == "not"):
            if materializing:
                # materialize_condition handles these before this branch; this is defensive.
                raise CompileError("internal error: recursive boolean condition lowering")
            value = self.materialize_condition(expression)
            return self.ref_equals_params(value, "1")

        value = self.require_value(self.emit_expr(expression), context="if condition")
        expression_type = self.expr_type(expression)
        if expression_type in {"number", "bool"}:
            return {
                "WFInput": value.condition_input(),
                "WFCondition": 5,
                "WFConditionalActionString": "0",
            }
        if expression_type == "none":
            # A None literal is caught by materialize_condition, but a None-typed variable may land here.
            return {"WFInput": value.condition_input(), "WFCondition": 101}
        return {"WFInput": value.condition_input(), "WFCondition": 100}

    @staticmethod
    def ref_equals_params(value: ValueRef, expected: str) -> dict[str, PlistValue]:
        return {
            "WFInput": value.condition_input(),
            "WFCondition": 4,
            "WFConditionalActionString": expected,
        }

    def expr_type(self, expression: ir.Expr) -> str:
        if isinstance(expression, ir.Literal):
            if expression.value is None:
                return "none"
            if isinstance(expression.value, bool):
                return "bool"
            if isinstance(expression.value, (int, float)):
                return "number"
            if isinstance(expression.value, str):
                return "text"
        if isinstance(expression, ir.Var):
            return self.var_types.get(expression.name, "unknown")
        if isinstance(expression, ir.BlockExpr):
            return self.expr_type(expression.result)
        if isinstance(expression, (ir.Compare, ir.BoolExpr)) or (
            isinstance(expression, ir.Unary) and expression.op == "not"
        ):
            return "bool"
        if isinstance(expression, ir.Binary):
            return "number"
        if isinstance(expression, ir.FormatString):
            return "text"
        if isinstance(expression, ir.ListExpr):
            return "list"
        if isinstance(expression, ir.DictExpr):
            return "dict"
        if isinstance(expression, ir.Call):
            if expression.target == "input":
                return "text"
            if expression.target == "len":
                return "number"
            return self.plugins.result_type(expression.target)
        return "unknown"

    def text_param(self, expression: ir.Expr) -> PlistValue:
        if isinstance(expression, ir.Literal) and isinstance(expression.value, str):
            return expression.value
        if isinstance(expression, ir.FormatString):
            return self.text_token_from_parts(expression.parts)
        value = self.require_value(self.emit_expr(expression), context="text parameter")
        return self.text_token_from_refs((value,))

    def text_token_from_parts(self, parts: tuple[str | ir.Expr, ...]) -> PlistValue:
        string_parts: list[str] = []
        refs: list[tuple[int, ValueRef]] = []
        utf16_offset = 0
        for part in parts:
            if isinstance(part, str):
                string_parts.append(part)
                utf16_offset += len(part.encode("utf-16-le")) // 2
                continue
            if isinstance(part, ir.Literal) and isinstance(part.value, str):
                text = part.value
                string_parts.append(text)
                utf16_offset += len(text.encode("utf-16-le")) // 2
                continue
            value = self.require_value(self.emit_expr(part), context="formatted text")
            string_parts.append("\ufffc")
            refs.append((utf16_offset, value))
            utf16_offset += 1
        if not refs:
            return "".join(string_parts)
        attachments = {f"{{{offset}, 1}}": ref.value() for offset, ref in refs}
        return {
            "Value": {"string": "".join(string_parts), "attachmentsByRange": attachments},
            "WFSerializationType": "WFTextTokenString",
        }

    def text_token_from_refs(self, refs: tuple[ValueRef, ...]) -> dict[str, PlistValue]:
        string = "\ufffc" * len(refs)
        attachments = {f"{{{index}, 1}}": ref.value() for index, ref in enumerate(refs)}
        return {
            "Value": {"string": string, "attachmentsByRange": attachments},
            "WFSerializationType": "WFTextTokenString",
        }

    @staticmethod
    def static_text_token(text: str) -> dict[str, PlistValue]:
        return {
            "Value": {"string": text, "attachmentsByRange": {}},
            "WFSerializationType": "WFTextTokenString",
        }

    def require_value(self, value: ValueRef | None, *, context: str) -> ValueRef:
        if value is None:
            raise CompileError(f"{context} requires a value, but the expression is side-effect-only")
        return value

    @staticmethod
    def scalar_text(value: ir.Scalar) -> str:
        if value is None:
            return ""
        if value is True:
            return "1"
        if value is False:
            return "0"
        return str(value)

    @staticmethod
    def new_uuid() -> str:
        return str(uuid.uuid4()).upper()

    def new_temp_variable(self, prefix: str) -> str:
        self._temp_counter += 1
        return f"__py2s_{prefix}_{self._temp_counter}"

    def repeat_variable_name(self, base: str) -> str:
        if self.loop_depth <= 1:
            return base
        return f"{base} {self.loop_depth}"

    def require_literal_string(self, expression: ir.Expr | None, *, default: str, name: str) -> str:
        if expression is None:
            return default
        if isinstance(expression, ir.Literal) and isinstance(expression.value, str):
            return expression.value
        raise CompileError(f"{name} must be a literal string")

    def static_value(self, expression: ir.Expr) -> PlistValue:
        if isinstance(expression, ir.Literal):
            value = expression.value
            if value is None:
                return ""
            return value
        if isinstance(expression, ir.ListExpr):
            return [self.static_value(item) for item in expression.items]
        if isinstance(expression, ir.DictExpr):
            out: dict[str, PlistValue] = {}
            for key, value in expression.items:
                if not isinstance(key, ir.Literal) or not isinstance(key.value, str):
                    raise CompileError("raw action dictionary keys must be literal strings")
                out[key.value] = self.static_value(value)
            return out
        raise CompileError("raw action parameters must be compile-time literals")


def _expect_arg(call: ir.Call, index: int, name: str) -> ir.Expr:
    try:
        return call.args[index]
    except IndexError as error:
        raise CompileError(f"{call.target}() is missing required argument {name!r}") from error


def _plugin_comment(backend: ShortcutsBackend, call: ir.Call) -> None:
    if len(call.args) != 1 or call.kwargs:
        raise CompileError("shortcuts.comment() expects one literal string")
    text = backend.static_value(call.args[0])
    if not isinstance(text, str):
        raise CompileError("shortcuts.comment() text must be a literal string")
    backend.actions.append(action("comment", WFCommentActionText=text))
    return None


def _plugin_notification(backend: ShortcutsBackend, call: ir.Call) -> None:
    if not 1 <= len(call.args) <= 2:
        raise CompileError("shortcuts.notification(body, title='') expects one or two positional arguments")
    if {name for name, _ in call.kwargs} - {"title"}:
        raise CompileError("shortcuts.notification() only accepts title= as a keyword")
    body = backend.text_param(call.args[0])
    if len(call.args) == 2 and call.keyword("title") is not None:
        raise CompileError("shortcuts.notification(): title supplied twice")
    title_expr = call.args[1] if len(call.args) == 2 else call.keyword("title")
    params: dict[str, PlistValue] = {"WFNotificationActionBody": body}
    if title_expr is not None:
        params["WFNotificationActionTitle"] = backend.text_param(title_expr)
    backend.actions.append(action("notification", **params))
    return None


def _plugin_alert(backend: ShortcutsBackend, call: ir.Call) -> None:
    if not 1 <= len(call.args) <= 2:
        raise CompileError("shortcuts.alert(message, title='') expects one or two positional arguments")
    if {name for name, _ in call.kwargs} - {"title"}:
        raise CompileError("shortcuts.alert() only accepts title= as a keyword")
    message = backend.text_param(call.args[0])
    if len(call.args) == 2 and call.keyword("title") is not None:
        raise CompileError("shortcuts.alert(): title supplied twice")
    title_expr = call.args[1] if len(call.args) == 2 else call.keyword("title")
    params: dict[str, PlistValue] = {"WFAlertActionMessage": message}
    if title_expr is not None:
        params["WFAlertActionTitle"] = backend.text_param(title_expr)
    backend.actions.append(action("alert", **params))
    return None


def _plugin_get_url(backend: ShortcutsBackend, call: ir.Call) -> ValueRef:
    if len(call.args) != 1:
        raise CompileError("shortcuts.get_url(url, method='GET') expects one positional URL")
    if {name for name, _ in call.kwargs} - {"method"}:
        raise CompileError("shortcuts.get_url() only accepts method= as a keyword")
    method_expr = call.keyword("method")
    method = backend.require_literal_string(method_expr, default="GET", name="HTTP method").upper()
    result = action("downloadurl", WFURL=backend.text_param(call.args[0]), WFHTTPMethod=method)
    backend.actions.append(result)
    return ValueRef.action(result, "Contents of URL")


def _plugin_open_url(backend: ShortcutsBackend, call: ir.Call) -> None:
    if len(call.args) != 1 or call.kwargs:
        raise CompileError("shortcuts.open_url(url) expects one argument")
    url_action = action("url", WFURLActionURL=backend.text_param(call.args[0]))
    backend.actions.append(url_action)
    url = ValueRef.action(url_action, "URL")
    backend.actions.append(action("openurl", WFInput=url.attachment()))
    return None


def _plugin_raw_action(backend: ShortcutsBackend, call: ir.Call) -> ValueRef | None:
    if len(call.args) != 1:
        raise CompileError("shortcuts.raw_action(identifier, **parameters) expects one identifier")
    identifier_value = backend.static_value(call.args[0])
    if not isinstance(identifier_value, str) or "." not in identifier_value:
        raise CompileError("raw action identifier must be a literal reverse-DNS string")
    params: dict[str, PlistValue] = {}
    output_name: str | None = None
    for key, value_expr in call.kwargs:
        if key == "output":
            output = backend.static_value(value_expr)
            if output is not None and not isinstance(output, str):
                raise CompileError("raw_action output= must be a literal string")
            output_name = output
            continue
        params[key] = backend.static_value(value_expr)
    result = raw_action(identifier_value, **params)
    backend.actions.append(result)
    if output_name:
        return ValueRef.action(result, output_name)
    return None


def default_plugin_registry() -> PluginRegistry:
    registry = PluginRegistry()
    registry.register_call("shortcuts.comment", _plugin_comment)
    registry.register_call("shortcuts.notification", _plugin_notification)
    registry.register_call("shortcuts.alert", _plugin_alert)
    registry.register_call("shortcuts.get_url", _plugin_get_url)
    registry.register_call("shortcuts.open_url", _plugin_open_url)
    registry.register_call("shortcuts.raw_action", _plugin_raw_action)

    # Keep first-party iOS/Shortcuts knowledge out of the compiler frontend.
    # The local import avoids a module cycle while this backend module is loading.
    from .ios import register_ios_plugins

    register_ios_plugins(registry)

    from .stdlib import register_stdlib_plugins

    register_stdlib_plugins(registry)
    return registry
